import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { About, Banner } from "../components/home";
import styles from "../styles/Home.module.css";
import ProjectList from "../components/home/ProjectList";
import SkillList from "../components/home/SkillList";
import Contact from "../components/home/Contact";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <About />
      <ProjectList />
      <SkillList />
      <Contact />
    </div>
  );
}
